### ISSUE TITLE
Comment in StringCheese.m needs to be updated. 

### ISSUE THREAD

**Issue by brianllamar** [Bloc/ios-exercises#108]
There is a comment (line 30 and 47) in [StringCheese.m](https://github.com/Bloc/ios-exercises/blob/master/BlocExercises/BlocExercises/StringCheese.m) stating you will learn more about if/else in the next checkpoint, but the next checkpoint is on Equality. This might need to be updated to state you will learn about "if/else" in a "future" checkpoint. 
```
    /*
     (You will learn more about if/else statements in the next checkpoint.)
     */
```

**Comment by brianllamar** [comment]
On second thought, I have just completed the Equality Checkpoint and realized that Equality is a great intro to how if/else works. I leave this with your discretion.

**Comment by getaaron** [comment]
Thanks, @brianllamar. I updated the comment, per your suggestion, in https://github.com/Bloc/ios-exercises/commit/df954b47a95c1fb8471fea0b267fe941adc3e186.
