### ISSUE TITLE
StringCheese.m has not needed if/else statement

### ISSUE THREAD

**Issue by mknippen** [Bloc/ios-exercises#145]
In the cheeseNameWithoutCheeseSuffix method, an if statement was added to see if it contained cheese. 

I use this as a good place to explore the documentation with my students, and there's a method in NSString that's designed to handle this exact problem, without an if statement. To me, the best answer would be as follows:

    NSString *nameNoCheese = [cheeseName stringByReplacingOccurrencesOfString:@" cheese" withString:@"" options:NSCaseInsensitiveSearch range:NSMakeRange(0, cheeseName.length)];

Can we remove the if statement so both answers could be acceptable?

Thanks!

**Comment by getaaron** [comment]
@mknippen How do you feel about this? https://github.com/Bloc/ios-exercises/pull/146
